services:
  islandty:
    image: islandty:latest
    command: sh -c "npm start"
    ports:
      - 8080:8080
    working_dir: /islandty
    volumes:
      - ../islandora_demo_objects:/islandty/islandora_demo_objects
      - ./web:/islandty/web
    environment:
      inputMediaPath: ./islandora_demo_objects
      dataFileName: ./islandora_demo_objects/create_islandora_objects.csv
